// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoZamJ9Ess1WudaAEaS50aRrFAXrI5V0',
    appId: '1:157494589178:web:7bc3ffd43d4bc50de3bb43',
    messagingSenderId: '157494589178',
    projectId: 'insurances-management',
    authDomain: 'insurances-management.firebaseapp.com',
    storageBucket: 'insurances-management.appspot.com',
    measurementId: 'G-66SP1010XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9ULJwbAXGXiMt5PEo-4GGQZdRfjbYKQ',
    appId: '1:157494589178:android:98eab4a3bb59a8cde3bb43',
    messagingSenderId: '157494589178',
    projectId: 'insurances-management',
    storageBucket: 'insurances-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXKmDaWEzhqK6lEnAd8ertpD0ybEaYOc',
    appId: '1:157494589178:ios:7452175ca18f615fe3bb43',
    messagingSenderId: '157494589178',
    projectId: 'insurances-management',
    storageBucket: 'insurances-management.appspot.com',
    iosClientId: '157494589178-e1p7u2os29v30usjfo728ll8btt502ci.apps.googleusercontent.com',
    iosBundleId: 'com.foudhaili.insurances',
  );
}
